seed: 546
batch_size: 2
num_workers: 30

gpus: 4
accumulate_grad_batches: 1
default_root_dir: /home/sr2369/inpainting
checkpoint_dir: checkpoints_normalized_output_c128
voxel_dir: max_area_3d_voxel
default_root_dir_postfix: ''
resume_from_checkpoint: /home/sr2369/inpainting/checkpoints_normalized_output_c128/epoch_epoch=129_step_step=108060.ckpt
max_steps: -1
max_epochs: -1
precision: 32
gradient_clip_val: 1.0


embedding_dim: 128
n_codes: 16384
n_hiddens: 128
lr: 3e-4
downsample: [2, 2, 2]
disc_channels: 64
disc_layers: 3
discriminator_iter_start: 20000
disc_loss_type: hinge
image_gan_weight: 1.0
video_gan_weight: 1.0
l1_weight: 4.0
gan_feat_weight: 0.0
perceptual_weight: 0.0
i3d_feat: False
restart_thres: 1.0
no_random_restart: False
norm_type: group
padding_type: replicate
num_groups: 32

wandb_project_name: vqgan-cspca
normalize: True

